### ISSUE TITLE
Change theme problem

### ISSUE THREAD

**Issue by phuongtailtranminh** [Stanford-Online/edx-theme#36]
Hi,

I'm using Eucalyptus

After I changed theme by following your guideline (README) and restart server, I got "Internal Error"

Is there any extra step?

**Comment by Pipar** [comment]
Hi

Sorry i can't help as I can't fix that problem myself. I have open edx up
and running but the theme still just empty.

I followed the directions that i found on the web but not working :-(

If you find away would like to hear it :-)



Jeff

**Comment by SamuelMarks** [comment]
@phuongtailtranminh Are you planning on adding ficus support?

**Comment by phuongtailtranminh** [comment]
@SamuelMarks , sorry, I don't have solution for this problem

**Comment by SamuelMarks** [comment]
Oh whoops, meant to reference the maintainer @caesar2164

**Comment by caesar2164** [comment]
@SamuelMarks I'm not sure what you're referring to? Can I get some more context?

**Comment by SamuelMarks** [comment]
@caesar2164 I am interested in installed the lagunita—or older Stanford theme—in the latest OpenEdX distributed, i.e.: ficus.3.

How am I meant to install it, and if changes need to be made to make it compatible, can you drop some hints and I'll give a PR a go?

**Comment by caesar2164** [comment]
@SamuelMarks I would strongly suggest you look into using the newer "Comprehensive Theming" method now available by default in platform.

for a rough idea of how it works to convert from Stanford theming to Comp Theming see this PR: https://github.com/Stanford-Online/lagunita-theme/pull/56
